"use client";

import { useRef, useState } from "react";
import { useTranslations } from "next-intl";
import { Turnstile } from "@marsidev/react-turnstile";
import { Icon } from "@/components/icons";
import { FlowFooter } from "@/components/flow-shell";
import { useFlow } from "@/components/flow-provider";
import { useRouter } from "@/i18n/navigation";
import { PRICES, type PaymentMethod } from "@/lib/flow-data";

const ZELLE_EMAIL = process.env.NEXT_PUBLIC_ZELLE_EMAIL || "pay@mongolstay.com";
const ZELLE_NAME = process.env.NEXT_PUBLIC_ZELLE_NAME || "Mongolstay PLLC";
const TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;

export function PaymentStep() {
  const { kind, state, setState } = useFlow();
  const router = useRouter();
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const turnstileToken = useRef<string | null>(null);
  const t = useTranslations("flow.pay");
  const tBtn = useTranslations("flow.buttons");
  const { fee, uscisFee } = PRICES[kind];
  const total = fee + uscisFee;
  const totalStr = total.toLocaleString();

  const method: PaymentMethod = state.payment.method ?? "card";
  const setMethod = (m: PaymentMethod) =>
    setState((s) => ({ ...s, payment: { ...s.payment, method: m } }));

  // Stable reference (generated by FlowProvider on mount).
  const reference = state.reference;

  const submitIntake = async (chosen: PaymentMethod) => {
    const res = await fetch("/api/intake/submit", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        kind,
        reference,
        contact: state.contact,
        answers: state.answers,
        schedule:
          state.schedule.mode === "appointment" && state.schedule.appointment
            ? { mode: "appointment", iso: state.schedule.appointment.iso, channel: state.schedule.appointment.channel }
            : state.schedule.mode === "callback" && state.schedule.callback
            ? { mode: "callback", window: state.schedule.callback.window, note: state.schedule.callback.note }
            : { mode: null },
        documents: state.documents,
        method: chosen,
        turnstileToken: turnstileToken.current,
      }),
    });
    if (!res.ok) {
      const text = await res.text();
      throw new Error(`submit failed (${res.status}): ${text}`);
    }
    return res.json() as Promise<{ url?: string; reference: string }>;
  };

  const startCard = async () => {
    setSubmitting(true);
    setError(null);
    try {
      const { url } = await submitIntake("card");
      setState((s) => ({ ...s, payment: { ...s.payment, method: "card", status: "pending", reference } }));
      if (url) { window.location.href = url; return; }
      // No Stripe URL (Stripe not configured) — fall through to filed page with awaiting status.
      setState((s) => ({ ...s, payment: { ...s.payment, method: "card", status: "awaiting", reference } }));
      router.push(`/file/${kind}/filed`);
    } catch (e) {
      console.error(e);
      setError((e as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  const confirmManual = async (chosen: "zelle" | "cash") => {
    setSubmitting(true);
    setError(null);
    try {
      await submitIntake(chosen);
      setState((s) => ({ ...s, payment: { ...s.payment, method: chosen, status: "awaiting", reference } }));
      router.push(`/file/${kind}/filed`);
    } catch (e) {
      console.error(e);
      setError((e as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  const onNext = () => {
    if (method === "card") return startCard();
    if (method === "zelle") return confirmManual("zelle");
    if (method === "cash") return confirmManual("cash");
  };

  const nextLabel = (() => {
    if (submitting) return tBtn("redirecting");
    if (method === "card") return tBtn("pay", { total: totalStr });
    if (method === "zelle") return t("methods.zelle.cta");
    return t("methods.cash.cta");
  })();

  return (
    <>
      <div className="pay">
        <div className="pay-grid">
          <div className="pay-form">
            <div className="pay-methods" role="tablist">
              {(["card", "zelle", "cash"] as PaymentMethod[]).map((m) => (
                <button
                  key={m}
                  type="button"
                  role="tab"
                  aria-selected={method === m}
                  className={`pay-method ${method === m ? "sel" : ""}`}
                  onClick={() => setMethod(m)}
                >
                  {m === "card" && <Icon.Card style={{ width: 16, height: 16 }} />}
                  {m === "zelle" && <Icon.Lock style={{ width: 16, height: 16 }} />}
                  {m === "cash" && <Icon.Calendar style={{ width: 16, height: 16 }} />}
                  <span>{t(`methods.${m}.label`)}</span>
                </button>
              ))}
            </div>

            {method === "card" && (
              <div className="pay-method-body">
                <p>{t("methods.card.body", { total: totalStr })}</p>
                <div className="pay-secured">
                  <Icon.Lock style={{ width: 13, height: 13 }} /> {t("secured")}
                </div>
              </div>
            )}

            {method === "zelle" && (
              <div className="pay-method-body">
                <p>{t("methods.zelle.body", { total: totalStr })}</p>
                <div className="pay-instruction">
                  <div className="pay-instruction-row">
                    <span className="pay-instruction-lbl">{t("methods.zelle.sendTo")}</span>
                    <span className="mono">{ZELLE_EMAIL}</span>
                  </div>
                  <div className="pay-instruction-row">
                    <span className="pay-instruction-lbl">{t("methods.zelle.recipient")}</span>
                    <span>{ZELLE_NAME}</span>
                  </div>
                  <div className="pay-instruction-row">
                    <span className="pay-instruction-lbl">{t("methods.zelle.amount")}</span>
                    <span className="mono">${totalStr}.00</span>
                  </div>
                  <div className="pay-instruction-row">
                    <span className="pay-instruction-lbl">{t("methods.zelle.memo")}</span>
                    <span className="mono">{reference}</span>
                  </div>
                </div>
                <p className="pay-instruction-foot">{t("methods.zelle.foot")}</p>
              </div>
            )}

            {method === "cash" && (
              <div className="pay-method-body">
                <p>{t("methods.cash.body", { total: totalStr })}</p>
                <div className="pay-instruction">
                  <div className="pay-instruction-row">
                    <span className="pay-instruction-lbl">{t("methods.cash.amount")}</span>
                    <span className="mono">${totalStr}.00</span>
                  </div>
                  <div className="pay-instruction-row">
                    <span className="pay-instruction-lbl">{t("methods.cash.reference")}</span>
                    <span className="mono">{reference}</span>
                  </div>
                </div>
                <p className="pay-instruction-foot">{t("methods.cash.foot")}</p>
              </div>
            )}

            {TURNSTILE_SITE_KEY && (
              <div className="pay-turnstile">
                <Turnstile
                  siteKey={TURNSTILE_SITE_KEY}
                  onSuccess={(token) => { turnstileToken.current = token; }}
                  onExpire={() => { turnstileToken.current = null; }}
                  onError={() => { turnstileToken.current = null; }}
                />
              </div>
            )}

            {error && (
              <div className="field-err" role="alert" style={{ marginTop: 8 }}>
                {error}
              </div>
            )}
          </div>

          <div className="pay-summary">
            <div className="pay-sum-h">{t("summary")}</div>
            <div className="pay-sum-row">
              <span>{t(`${kind}Line`)}</span>
              <span className="mono">${fee.toLocaleString()}.00</span>
            </div>
            {uscisFee > 0 && (
              <div className="pay-sum-row muted">
                <span>{t("uscisFee")}</span>
                <span className="mono">${uscisFee}.00</span>
              </div>
            )}
            <div className="pay-sum-row muted"><span>{t("attorneyReview")}</span><span>{t("included")}</span></div>
            <div className="pay-sum-row muted"><span>{t("appointmentIncl")}</span><span>{t("included")}</span></div>
            <div className="pay-sum-divider" />
            <div className="pay-sum-row total">
              <span>{t("total")}</span>
              <span className="mono">${totalStr}.00</span>
            </div>
            <div className="pay-sum-foot">
              {t("footFlat")} {kind === "asylum" ? t("footAsylum") : ""}
            </div>
          </div>
        </div>
      </div>

      <FlowFooter
        prevHref={`/file/${kind}/schedule`}
        nextLabel={nextLabel}
        nextDisabled={submitting}
        onNext={onNext}
      />
    </>
  );
}
